services:
  # ---------- Infrastructure ----------
  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - ride-flow-user-db:/var/lib/postgresql/data

  mongo-driver:
    image: mongo:8.0.15
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_root_pass
    ports:
      - "27017:27017"
    volumes:
      - ride-flow-driver-db:/data/db
      - ./mongo/mongo-driver-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ride-flow-keycloak-db:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    command:
      - start-dev
#      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_PORT: 8080
    volumes:
      - ./keycloak/rideflow-realm.json:/opt/keycloak/data/import/rideflow-realm.json
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db

volumes:
  ride-flow-user-db: {}
  ride-flow-keycloak-db: {}
  ride-flow-driver-db: {}