services:
  # ---------- Infrastructure ----------
  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - ride-flow-user-db:/var/lib/postgresql/data

  mongo-driver:
    image: mongo:8.0.15
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_root_pass
    ports:
      - "27017:27017"
    volumes:
      - ride-flow-driver-db:/data/db
      - ./mongo/mongo-driver-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ride-flow-keycloak-db:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    command:
      - start-dev
    #      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_PORT: 8080
    volumes:
      - ./keycloak/rideflow-realm.json:/opt/keycloak/data/import/rideflow-realm.json
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db

  # ---------- Services ----------
  gateway-service:
    image: gateway-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - USER_SERVICE_URL=http://user-service:8082
      - ISSUER_URL=http://keycloak:8080/realms/rideflow

  user-service:
    image: user-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres-user
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-user:5432/userdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - DRIVER_SERVICE_URL=http://driver-service:8083
      - ISSUER_URL=http://keycloak:8080/realms/rideflow

  driver-service:
    image: driver-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - mongo-driver
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGO_HOST=mongo-driver
      - MONGO_PORT=27017
      - MONGO_DB_NAME=driverdb
      - MONGO_USER=driverappuser
      - MONGO_PASSWORD=driverappsecret
      - ISSUER_URL=http://keycloak:8080/realms/rideflow

volumes:
  ride-flow-user-db: { }
  ride-flow-keycloak-db: { }
  ride-flow-driver-db: { }