server:
  port: 8082
  servlet:
    context-path: /api/${user-service.api-path-version}

spring:
  application:
    name: user-service
  cloud:
    openfeign:
      client:
        config:
          driver-service:
            url: ${DRIVER_SERVICE_URL:http://localhost:8083}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:8081/realms/rideflow}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${DB_USER:user}
    password: ${DB_PASS:user}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs

user-service:
  api-path-version: v1
  api-version: 1.0.0
  api-title: RideFlow User Service API
  api-description: REST API for managing RideFlow users (riders & drivers).