server:
  port: 8083
  servlet:
    context-path: /api/${driver-service.api-path-version}

spring:
  application:
    name: driver-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB_NAME:driverdb}
      username: ${MONGO_USER:driverappuser}
      password: ${MONGO_PASSWORD:driverappsecret}
      uuid-representation: standard
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:8081/realms/rideflow}

springdoc:
  api-docs:
    path: /api-docs

driver-service:
  api-path-version: v1
  api-version: 1.0.0
  api-title: RideFlow Driver Service API
  api-description: REST API for managing RideFlow drivers.